services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles: [backend]
  db:
    image: postgres
    container_name: travel_planner_postgres
    env_file: "env.properties"
    restart: unless-stopped
    ports:
      - "5400:5432"
    shm_size: 128mb # shared memory limit
