GET http://localhost:8080/api/city

###
POST http://localhost:8080/api/city
Content-Type: application/json

{
  "name": "Timis"
}
###
POST http://localhost:8080/api/city
Content-Type: application/json

{
  "id": 30,
  "name": "Arad"
}
###
DELETE http://localhost:8080/api/city/-9
###
DELETE http://localhost:8080/api/city/4
###
PUT http://localhost:8080/api/city/
Content-Type: application/json

{
  "id": 40,
  "name": "lol"
}
###
PUT http://localhost:8080/api/city/3
Content-Type: application/json

{
  "name": "Iasi"
}
###
PUT http://localhost:8080/api/city/2
###
POST http://localhost:8080/api/city/upload
Content-Type: application/json

[
  { "name": "A" },
  { "name": "Oradea" },
  { "name": "Sibiu" },
  { "name": "Brasov" },
  { "name": "Galati" }
]