spring:
  application:
    name: backend
  config:
    import: "optional:file:env.properties"

  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.flywaydb: INFO
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
