name: Release

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Github Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PROJECT_PAT  }}

      - name: 'Build Image'
        run: |
          docker build -t integra-team-red/travel-planner:latest .
          docker push integra-team-red/travel-planner:latest


